version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: ./node_modules/.bin/mocha test --reporter mocha-junit-reporter
      - store_test_results:
          path: test-results.xml
